In [ ]:
#Создание новой базы данных и подключение к существующей
import sqlite3

# Создаем подключение к базе данных (файл my_database.db будет создан)
connection = sqlite3.connect('my_database.db')

connection.close()
#DB Browser for SQLite (или SQLite Studio) - рафический интерфейс, позволяющий просматривать, редактировать и управлять данными в базе SQLite( sqlitebrowser.org)

In [ ]:
#Создание таблицы с определением структуры и типов данных
import sqlite3

# Устанавливаем соединение с базой данных
connection = sqlite3.connect('my_database.db')
cursor = connection.cursor()

# Создаем таблицу Users
cursor.execute('''
CREATE TABLE IF NOT EXISTS Users (
id INTEGER PRIMARY KEY,
username TEXT NOT NULL,
email TEXT NOT NULL,
age INTEGER
)
''')

# Сохраняем изменения и закрываем соединение
connection.commit()
connection.close()
#Мы по сути говорим питону:

#1. Подключись к базе данных 'my_database.db'

#2. Если таблица не существует (NOT EXISTS), то создай таблицу с названием "Users"

#3. Если таблица существует (EXISTS), то пропускай создание таблиц.

#4. Создай данные id как 'INTEGER', сделав первичным ключом.

#5. Создай username, email и без NULL (чтобы не был пустым)

#6. Сохрани изменение и закрой соединение.

In [ ]:
#Индексы и их роль в оптимизации запросов
import sqlite3

# Устанавливаем соединение с базой данных
connection = sqlite3.connect('my_database.db')
cursor = connection.cursor()

# Создаем индекс для столбца "email"
cursor.execute('CREATE INDEX idx_email ON Users (email)')
#Эта строка выполняет операцию SQL для создания индекса с именем "idx_email" для столбца "email" в таблице "Users".
#Индекс позволяет ускорить поиск и сортировку данных в столбце "email".
# Сохраняем изменения и закрываем соединение
connection.commit()
connection.close()

In [ ]:
#Использование оператора INSERT для добавления данных
import sqlite3

# Устанавливаем соединение с базой данных
connection = sqlite3.connect('my_database.db')
cursor = connection.cursor()

# Добавляем нового пользователя
cursor.execute('INSERT INTO Users (username, email, age) VALUES (?, ?, ?)', ('newuser', 'newuser@example.com', 28))

# Сохраняем изменения и закрываем соединение
connection.commit()
connection.close()

In [ ]:
#Обновление записей с использованием UPDATE
import sqlite3

# Устанавливаем соединение с базой данных
connection = sqlite3.connect('my_database.db')
cursor = connection.cursor()

# Обновляем возраст пользователя "newuser"
cursor.execute('UPDATE Users SET age = ? WHERE username = ?', (29, 'newuser'))

# Сохраняем изменения и закрываем соединение
connection.commit()
connection.close()

In [ ]:
#Удаление данных с помощью оператора DELETE
import sqlite3

# Устанавливаем соединение с базой данных
connection = sqlite3.connect('my_database.db')
cursor = connection.cursor()

# Удаляем пользователя "newuser"
cursor.execute('DELETE FROM Users WHERE username = ?', ('newuser',))

# Сохраняем изменения и закрываем соединение
connection.commit()
connection.close()

In [ ]:
#Использование SQL-запросов для извлечения данных из таблиц
import sqlite3

# Устанавливаем соединение с базой данных
connection = sqlite3.connect('my_database.db')
cursor = connection.cursor()

# Выбираем всех пользователей
cursor.execute('SELECT * FROM Users')
users = cursor.fetchall()

# Выводим результаты
for user in users:
  print(user)

# Закрываем соединение
connection.close()

In [ ]:
#Применение операторов SELECT, FROM, WHERE, GROUP BY, HAVING, ORDER BY
#Оператор SELECT позволяет выбрать определенные столбцы из таблицы
import sqlite3

connection = sqlite3.connect('my_database.db')
cursor = connection.cursor()

# Выбираем имена и возраст пользователей старше 25 лет
cursor.execute('SELECT username, age FROM Users WHERE age > ?', (25,))
#Эта строка выполняет операцию SQL для выбора имен и возрастов пользователей, возраст которых больше 25 лет. 
# Знак вопроса (?) является местозаполнителем для параметра в запросе, который будет заменен значением (в данном случае, числом 25) из второго аргумента метода execute().
results = cursor.fetchall()

for row in results:
  print(row)

connection.close()

In [ ]:
#Оператор GROUP BY используется для группировки данных по определенным столбцам
#Оператор HAVING применяется к агрегатным функциям, чтобы фильтровать результаты групп
import sqlite3

connection = sqlite3.connect('my_database.db')
cursor = connection.cursor()

# Получаем средний возраст пользователей для каждого возраста
cursor.execute('SELECT age, AVG(age) FROM Users GROUP BY age')
#выбирает возраст каждого пользователя и средний возраст всех пользователей для каждого возраста
#Оператор GROUP BY age группирует данные по возрасту
results = cursor.fetchall()

for row in results:
  print(row)
  
# Фильтруем группы по среднему возрасту больше 30
cursor.execute('SELECT age, AVG(age) FROM Users GROUP BY age HAVING AVG(age) > ?', (30,))
# делает то же самое, что и предыдущий запрос, но добавляет фильтрацию с помощью HAVING, которая ограничивает результаты только теми группами, где средний возраст больше 30
filtered_results = cursor.fetchall()
for row in filtered_results:
  print(row)

connection.close()

In [ ]:
#Оператор ORDER BY используется для сортировки результатов по указанным столбцам
import sqlite3

connection = sqlite3.connect('my_database.db')
cursor = connection.cursor()

# Выбираем и сортируем пользователей по возрасту по убыванию
cursor.execute('SELECT username, age FROM Users ORDER BY age DESC')
results = cursor.fetchall()

for row in results:
  print(row)

connection.close()

In [ ]:
#Использование агрегатных функций: COUNT, SUM, AVG, MIN, MAX(агрегатные функции)
#Функция COUNT используется для подсчета количества записей в столбце или таблице
import sqlite3

connection = sqlite3.connect('my_database.db')
cursor = connection.cursor()

# Подсчет общего числа пользователей
cursor.execute('SELECT COUNT(*) FROM Users')
total_users = cursor.fetchone()[0]

print('Общее количество пользователей:', total_users)
connection.close()

In [ ]:
#Функция SUM вычисляет сумму числовых значений в столбце
import sqlite3

connection = sqlite3.connect('my_database.db')
cursor = connection.cursor()

# Вычисление суммы возрастов пользователей
cursor.execute('SELECT SUM(age) FROM Users')
total_age = cursor.fetchone()[0]

print('Общая сумма возрастов пользователей:', total_age)
connection.close()

In [ ]:
#Функция AVG вычисляет среднее значение числовых данных в столбце
import sqlite3

connection = sqlite3.connect('my_database.db')
cursor = connection.cursor()

# Вычисление среднего возраста пользователей
cursor.execute('SELECT AVG(age) FROM Users')
average_age = cursor.fetchone()[0]

print('Средний возраст пользователей:', average_age)
connection.close()

In [ ]:
#Функция MIN находит минимальное значение в столбце
import sqlite3

connection = sqlite3.connect('my_database.db')
cursor = connection.cursor()

# Нахождение минимального возраста
cursor.execute('SELECT MIN(age) FROM Users')
min_age = cursor.fetchone()[0]

print('Минимальный возраст среди пользователей:', min_age)
connection.close()

In [ ]:
#Функция MAX находит максимальное значение в столбце
import sqlite3
connection = sqlite3.connect('my_database.db')
cursor = connection.cursor()

# Нахождение максимального возраста
cursor.execute('SELECT MAX(age) FROM Users')
max_age = cursor.fetchone()[0]

print('Максимальный возраст среди пользователей:', max_age)
connection.close()

In [ ]:
#Примеры сложных запросов с объединением таблиц и подзапросами
import sqlite3

# Устанавливаем соединение с базой данных
connection = sqlite3.connect('my_database.db')
cursor = connection.cursor()

# Находим пользователей с наибольшим возрастом
cursor.execute('''
SELECT username, age
FROM Users
WHERE age = (SELECT MAX(age) FROM Users)
''')
oldest_users = cursor.fetchall()

# Выводим результаты
for user in oldest_users:
  print(user)
  
# Закрываем соединение
connection.close()

In [ ]:
#Получение результатов запроса в виде списка кортежей
import sqlite3

# Устанавливаем соединение с базой данных
connection = sqlite3.connect('my_database.db')
cursor = connection.cursor()

# Выбираем всех пользователей
cursor.execute('SELECT * FROM Users')
users = cursor.fetchall()

# Выводим результаты
for user in users:
  print(user)
  
# Закрываем соединение
connection.close()

In [ ]:
#Использование методов fetchone(), fetchmany() и fetchall() для получения данных
import sqlite3

# Устанавливаем соединение с базой данных
connection = sqlite3.connect('my_database.db')
cursor = connection.cursor()

# Выбираем первого пользователя
cursor.execute('SELECT * FROM Users')
first_user = cursor.fetchone()
print(first_user)

# Выбираем первых 5 пользователей
cursor.execute('SELECT * FROM Users')
first_five_users = cursor.fetchmany(5)
print(first_five_users)

# Выбираем всех пользователей
cursor.execute('SELECT * FROM Users')
all_users = cursor.fetchall()
print(all_users)

# Закрываем соединение
connection.close()